# Generated by Django 4.1 on 2022-08-17 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
    ]
